### ISSUE TITLE
host it as github page

### ISSUE THREAD

**Issue by qoomon** [emilianoeloi/gitlab-ci-dashboard#36]

**Comment by emilianoeloi** [comment]
Hi Bengt, do you know how we can do it?

**Comment by qoomon** [comment]
just push the 'dist' folder to a branch called gh-pages within this repository then you can access it at https://emilianoeloi.github.io/gitlab-ci-dashboard

**Comment by emilianoeloi** [comment]
+ gitlab-ci-dashboard@6.0.0-alpha.4

**Comment by qoomon** [comment]
cool thank you
