### ISSUE TITLE
"build.project_build_url" is used in Builds.vue but not set anywhere

### ISSUE THREAD

**Issue by swordsp** [emilianoeloi/gitlab-ci-dashboard#42]
It only appears in Builds.vue in the whole repository:
https://github.com/emilianoeloi/gitlab-ci-dashboard/search?utf8=%E2%9C%93&q=project_build_url&type=

**Comment by emilianoeloi** [comment]
+ gitlab-ci-dashboard@5.6.0-alpha.2
