### ISSUE TITLE
Wrong behaviour when using manual stages

### ISSUE THREAD

**Issue by marek-ganko** [emilianoeloi/gitlab-ci-dashboard#47]
If pipelines of your projects contains manual stages they are wrongly handled by the gitlab-ci-dashboard.

Let's assume we have a pipeline with three stages where last two of them are manual.
After pipeline starts,  dashboard receives the statuses of the manual stages: `created` and then `manual`.

![gitlab-ci-stages](https://user-images.githubusercontent.com/6524355/35674462-b4e1553a-077f-11e8-8bc9-ddafc2718004.png)

With current implementation dashboard will show white card even though current status in Gitlab is `running` or `success`.

![dashboard-with-white-card](https://user-images.githubusercontent.com/6524355/35674628-34f3d3ce-0780-11e8-9a58-53de3f3e4c43.png)

BTW. I alreadt have a fix, will post it later

**Comment by emilianoeloi** [comment]
Nice! Thank you, Marek.

I had already detected this problem and was hoping to take some time to sort it out.

Thanks again and I await your PR.

Emiliano
