### ISSUE TITLE
Standalone version with URL parameters

### ISSUE THREAD

**Issue by marek-ganko** [emilianoeloi/gitlab-ci-dashboard#56]
I have a proposal to provide a possibility to handle URL parameters for the standalone version like: gitlab, token or projects/projetsFile.
Currently I need to setup whole project to have that option.

**Comment by marek-ganko** [comment]
@emilianoeloi What do you think about this proposal?

**Comment by emilianoeloi** [comment]
Hello, Marek. Sorry for the delay. I'm not sure I got this right. Could you tell me more about it?

**Comment by marek-ganko** [comment]
Hi Emiliano,

I'm missing functionality to run gitlab-ci-dashboard with posibility to configure it only from url by passing token and projectsFile, same as if you setup whole project from scratch. I've already changed the script, i'll add a PR soon.

**Comment by emilianoeloi** [comment]
+ gitlab-ci-dashboard@6.2.0-alpha.1
