### ISSUE TITLE
Can't find variable: getTopItemByName

### ISSUE THREAD

**Issue by ismael-gonzalez-sierra** [emilianoeloi/gitlab-ci-dashboard#66]
I am using Stallone version as global module, when I execute as following:

`gitlab-ci-dashboard --config ./config.json`

My config.json:

```
{
  "dashboard": {
    "config": {
      "gitlab": "My Gitlab-CE server",
      "token": "My token",
      "gitlabciProtocol": "https",
      "hideSuccessCards": false,
      "hideVersion": false,
      "interval": 60,
      "apiVersion": 4
    },
    "projects": [
      {
        "description": "My App Example iOS",
        "namespace": "IGS",
        "project": "MyApp-iOS",
        "branch": "develop"
      }
    ]
  }
}
```

When I access in browser I have this error:

> Something went wrong. Make sure the configuration is ok and your Gitlab is up and running. Details: Can't find variable: getTopItemByName

**Comment by emilianoeloi** [comment]
Hi Ismael. Correction on the way. Which browser do you use?

**Comment by emilianoeloi** [comment]
+ gitlab-ci-dashboard@6.4.0-alpha.2

**Comment by ismael-gonzalez-sierra** [comment]
Hi, i am using Safari, but I will can check with other browser. 

Thank
